version: '3.9'

services:
  web:
    image: "resgridllc/resgridwebcore:0.5.23"
    ports:
      - "5151:80"
    env_file:
      - resgrid.env
    depends_on:
      - api
      - events
      - db
      - redis
      - rabbitmq
      - worker
    environment:
      - WAIT_HOSTS=db:1433,redis:6379,rabbitmq:15672,api:80
      - WAIT_TIMEOUT=300

  api:
    image: "resgridllc/resgridwebservices:0.5.23"
    ports:
      - "5152:80"
    env_file:
      - resgrid.env
    depends_on:
      - events
      - db
      - redis
      - rabbitmq
      - worker
    environment:
      - WAIT_HOSTS=db:1433,redis:6379,rabbitmq:15672,events:80
      - WAIT_TIMEOUT=300

  events:
    image: "resgridllc/resgridwebevents:0.5.23"
    ports:
      - "5153:80"
    env_file:
      - resgrid.env
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - WAIT_HOSTS=db:1433,redis:6379,rabbitmq:15672
      - WAIT_AFTER=120
      - WAIT_TIMEOUT=300

  worker:
    image: "resgridllc/resgridworkersconsole:0.5.23"
    env_file:
      - resgrid.env
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - WAIT_HOSTS=db:1433,redis:6379,rabbitmq:15672
      - WAIT_AFTER=90
      - WAIT_TIMEOUT=180

  db:
    ports:
      - "5157:1433"
    build: ./db
    environment:
      - SA_PASSWORD=Resgrid123!!
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    volumes: 
      - type: "bind"
        source: ./docker-data/sql/data
        target: /var/opt/mssql/data
      - type: "bind"
        source: ./docker-data/sql/log
        target: /var/opt/mssql/log
      - type: "bind"
        source: ./docker-data/sql/backup
        target: /var/opt/mssql/backup

  redis:
    image: "redis:alpine"
    command: redis-server --save 60 1 --loglevel warning
    ports:
     - "5158:6379"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=resgrid
      - RABBITMQ_DEFAULT_PASS=Resgrid321!
    ports:
      - "5160:15672"
      - "5159:5672"

  elk:
    image: sebp/elk
    ports:
      - "5163:5601"
      - "5164:9200"
      - "5165:5044"
